services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    hostname: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    environment:
      HTTP_PROXY: http://192.168.0.102:7890
      HTTPS_PROXY: http://192.168.0.102:7890
      NO_PROXY: "localhost,127.0.0.1,0.0.0.0,172.*"
      no_proxy: "localhost,127.0.0.1,0.0.0.0,172.*"
      https_proxy: http://192.168.0.102:7890
      http_proxy: http://192.168.0.102:7890
    runtime: nvidia
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - genai_network
networks:
  genai_network: